const words=['CYBERSECURITY','ARTIFICIAL INTELLIGENCE','DATA ANALYTICS','WEB TECHNOLOGY','DIGITAL GROWTH'];let wi=0;setInterval(()=>{wi=(wi+1)%words.length;const el=document.getElementById('typeword');el.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:500});el.textContent=words[wi]},2200);
const credentials=[
['CISCO NETWORKING ACADEMY','Introduction to Cybersecurity','Security foundations and cybersecurity concepts.','assets/certificates/cisco-cybersecurity.pdf'],
['DELOITTE · FORAGE','Cyber Job Simulation','Practical cyber security tasks completed through a job simulation.','assets/certificates/deloitte-cyber.pdf'],
['TATA · FORAGE','Cybersecurity Analyst Job Simulation','IAM fundamentals, strategy assessment, custom solutions and platform integration.','assets/certificates/tata-cybersecurity.pdf'],
['DELOITTE · FORAGE','Data Analytics Job Simulation','Practical exposure to data analysis and forensic technology.','assets/certificates/deloitte-data.pdf'],
['MEITY · NASSCOM FUTURESKILLS','Yuva AI for All','Participation in a national digital skilling AI learning initiative.','assets/certificates/yuva-ai.pdf'],
['TDO TECH EDUCATION','Web Application Security','Security course covering web application penetration-testing requirements.','assets/certificates/web-app-security.pdf'],
['IIDE · THE DIGITAL SCHOOL','AI in Digital Marketing','Masterclass exploring AI applications in digital marketing.','assets/certificates/ai-digital-marketing.pdf'],
['IIDE · THE DIGITAL SCHOOL','ChatGPT Masterclass','Focused learning around ChatGPT and AI-assisted workflows.','assets/certificates/chatgpt-masterclass.pdf'],
['IIDE · THE DIGITAL SCHOOL','Fundamentals of Meta Advertising','Foundational learning in Meta advertising.','assets/certificates/meta-ads.pdf'],
['IIDE · THE DIGITAL SCHOOL','Instagram Marketing','Masterclass focused on Instagram marketing.','assets/certificates/instagram-marketing.pdf']];
const grid=document.getElementById('credentialGrid');credentials.forEach((c,i)=>{const a=document.createElement('article');a.className='credential'+(i>5?' hidden':'');a.innerHTML=`<span class="issuer">${c[0]}</span><h3>${c[1]}</h3><p>${c[2]}</p><button data-pdf="${c[3]}">VIEW CREDENTIAL ↗</button>`;grid.appendChild(a)});
document.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>{document.getElementById('certFrame').src=b.dataset.pdf;document.getElementById('modal').classList.add('open')});document.getElementById('close').onclick=()=>{document.getElementById('modal').classList.remove('open');document.getElementById('certFrame').src=''};
document.getElementById('showmore').onclick=function(){document.querySelectorAll('.credential.hidden').forEach(x=>x.classList.remove('hidden'));this.remove()};
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal,.domain,.build,.credential,.edu-card').forEach(x=>{x.classList.add('reveal');obs.observe(x)});document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.getElementById('nav').classList.remove('open'));document.getElementById('year').textContent=new Date().getFullYear();window.addEventListener('mousemove',e=>{const g=document.getElementById('glow');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});

// V3 interactive skill universe
(()=>{const c=document.getElementById('skillSphere');if(!c)return;const x=c.getContext('2d'),skills=['CYBERSECURITY','AI','DATA','JAVA','HTML','CSS','PROMPTING','CHATGPT','IAM','WEB SECURITY','ETHICAL HACKING','ANALYTICS','AUTOMATION','META ADS','DIGITAL MARKETING','INSTAGRAM','CHESS','CUBE SOLVING','MIND GAMES','TEACHING','COMPUTER SYSTEMS'];let pts=[],ax=.22,ay=.15,vx=.0008,vy=.0017,drag=false,lx=0,ly=0;
function size(){let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);c.width=r.width*d;c.height=r.height*d;x.setTransform(d,0,0,d,0,0);pts=skills.map((w,i)=>{let p=Math.acos(1-2*(i+.5)/skills.length),t=Math.PI*(1+Math.sqrt(5))*i;return{w,X:Math.sin(p)*Math.cos(t),Y:Math.cos(p),Z:Math.sin(p)*Math.sin(t)}})}
function rot(p){let X=p.X*Math.cos(ay)+p.Z*Math.sin(ay),Z=-p.X*Math.sin(ay)+p.Z*Math.cos(ay),Y=p.Y;return{X,Y:Y*Math.cos(ax)-Z*Math.sin(ax),Z:Y*Math.sin(ax)+Z*Math.cos(ax)}}
function frame(){let r=c.getBoundingClientRect(),cx=r.width/2,cy=r.height/2,R=Math.min(r.width,r.height)*.37;x.clearRect(0,0,r.width,r.height);if(!drag){ax+=vx;ay+=vy;vx*=.997;vy*=.997;if(Math.abs(vx)<.00035)vx=.00055;if(Math.abs(vy)<.0007)vy=.0011}pts.map(p=>({...p,q:rot(p)})).sort((a,b)=>a.q.Z-b.q.Z).forEach(p=>{let s=.65+(p.q.Z+1)*.27,a=.2+(p.q.Z+1)*.36;x.save();x.translate(cx+p.q.X*R,cy+p.q.Y*R);x.scale(s,s);x.font='600 15px Space Grotesk';x.textAlign='center';x.textBaseline='middle';x.fillStyle=`rgba(220,232,255,${a})`;x.fillText(p.w,0,0);x.restore()});requestAnimationFrame(frame)}
c.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drag)return;let dx=e.clientX-lx,dy=e.clientY-ly;ay+=dx*.008;ax+=dy*.008;vy=dx*.00014;vx=dy*.00014;lx=e.clientX;ly=e.clientY};c.onpointerup=c.onpointercancel=()=>drag=false;addEventListener('resize',size);size();frame()})();
